[theme]

# Primary accent for interactive elements
primaryColor = "#A0522D"  # A bardic warm brown

# Background color for the main content area
backgroundColor = '#FBFBFA'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#AD98B0'

# Color used for almost all text
textColor = '#2D2B3E'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"

[server]

# Enables support for Cross-Origin Resource Sharing (CORS) protection,
# for added security.
# If XSRF protection is enabled and CORS protection is disabled at the
# same time, Streamlit will enable them both instead.
# Default: true
enableCORS = false

# Enables support for Cross-Site Request Forgery (XSRF) protection, for
# added security.
# If XSRF protection is enabled and CORS protection is disabled at the
# same time, Streamlit will enable them both instead.
# Default: true
enableXsrfProtection = false